spring.application.name=jaubs-scopes

# Server runs on this port
server.port=8080

# Use this pattern to show reduced log width
logging.pattern.console= %d{HH:mm:ss} [%15thread] %msg%n

logging.level.web=TRACE
logging.level.org.springframework.web.client=TRACE

# KeyCloak specific OAuth 2 related properties
spring.security.oauth2.client.registration.keycloak-oidc.provider=keycloak
spring.security.oauth2.client.registration.keycloak-oidc.client-name=Keycloak
spring.security.oauth2.client.registration.keycloak-oidc.client-id=jaubs
spring.security.oauth2.client.registration.keycloak-oidc.client-secret=NPZcC0jXkjUTPmM8fdStuEtMqWgHlWF8
#spring.security.oauth2.client.registration.keycloak-oidc.client-authentication-method=none
spring.security.oauth2.client.registration.keycloak-oidc.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak-oidc.scope=openid,profile,email

# This represents the Keycloak Provider (issuer is enough for Spring Boot to know all endpoints)
# Openid configuration - http://127.0.0.1:9090/realms/oauthrealm/.well-known/openid-configuration
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://127.0.0.1:9090/realms/jaubsrealm

# # GitLab specific OAuth 2 related properties
# spring.security.oauth2.client.registration.gitlab-oidc.provider=gitlab
# spring.security.oauth2.client.registration.gitlab-oidc.client-name=GitLab
# spring.security.oauth2.client.registration.gitlab-oidc.client-id=<<gitlab-client-id>>
# spring.security.oauth2.client.registration.gitlab-oidc.client-secret=<<gitlab-client-secret>>
# spring.security.oauth2.client.registration.gitlab-oidc.authorization-grant-type=authorization_code
# spring.security.oauth2.client.registration.gitlab-oidc.scope=openid,profile,email

# # You need to set the issuer correctly (Not Strictly Required because its already known to Spring Boot)
# # Openid configuration - https://gitlab.com/.well-known/openid-configuration
# spring.security.oauth2.client.provider.gitlab.issuer-uri=https://gitlab.com
